// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laepalwqofgtujyqpqag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZXBhbHdxb2ZndHVqeXFwcWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDM5ODksImV4cCI6MjA3NDM3OTk4OX0.fGL_u6X5UtEvVI5xNAS8XVl9vmu3J0TifL0cGVHF0bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});